# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hblog
description: "" 
repository: https://github.com/framlog/framlog.github.io
baseurl: ""
url: https://framlog.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Huxley Hu
email: framlog#gmail.com

navigation:
  - text: Home
    url: /
  - text: About
    url: /about

social:
  - service: github
    username: framlog
    link: https://github.com/framlog

# Plugins
gems:
  - jekyll-seo-tag
